- package.json
- src/pages/home/HomeScreen.jsx
- src/pages/login/LoginScreen.jsx
> deploy: added gh-pages

- src/components/productList/ProductsList.jsx
- src/pages/manageProducts/ManageProductsScreen.jsx
> Alejandro fix bugs

- src/redux/actions/userActions.js
> fix: add return

- src/components/navbar/Navbar.jsx
Add useEffect to manage listener and resolve errors on Chrome dev tools terminal.
> fix: add useEffect to manage listener

- src/pages/shippingpay/ShippingPay.jsx
> fix: Removed unused useEffect

- src/pages/productDetails/ProductDetailsScreen.jsx
> fix: only remove console.log

- src/components/productList/ProductsList.jsx
> fix: comment console.log

- src/components/navbar/Navbar.jsx
Change position of menu option.
> refc: change position of menu options

- src/components/productList/ProductsList.jsx
- src/components/productList/ProductsList.module.css
> ImagesLink

- src/components/navbar/Navbar.jsx
- src/components/navbar/Navbar.module.css
- src/helpers/helpers.js
> refc: modified avatar dimensions

- src/pages/productDetails/ProductDetailsScreen.jsx
- src/redux/actions/ProductDetailsActions.js
> fix: comment unused constant

- src/components/navbar/Navbar.module.css
> refc: Modified favorite icon width

- src/components/footer/Footer.module.css
> editar footer se oculto tecnologias usadas

- src/pages/productDetails/ProductDetailsScreen.jsx
> fix: fixed

- src/routes/AppRouter.jsx
Now working ok when refresh the page.
> fix: now working ok when refresh the page

- src/components/productList/productsContainer.jsx
- src/redux/reducers/productReducer.js
> idPagination

- src/components/navbar/Navbar.jsx
- src/pages/productDetails/ProductDetailsScreen.jsx
> bugs Fixed

- src/components/navbar/Navbar.jsx
- src/pages/login/LoginScreen.css
- src/pages/login/LoginScreen.jsx
- src/pages/offersManager/OffersManager.jsx
- src/pages/register/RegisterScreen.css
- src/pages/register/RegisterScreen.jsx
- src/redux/actions/manageProductsActions.js
- src/routes/AppRouter.jsx
> Alejandro refactor after pull

- src/components/navbar/Navbar.jsx
- src/pages/login/LoginScreen.css
- src/pages/login/LoginScreen.jsx
- src/pages/productDetails/ProductDetailsScreen.jsx
- src/pages/register/RegisterScreen.css
> Fix small errors

- src/components/navbar/Navbar.module.css
- src/hooks/useForm.jsx
- src/pages/login/LoginScreen.jsx
- src/pages/register/RegisterScreen.jsx
- src/redux/actions/authActions.js
> Alejandro login

- src/pages/offersManager/OffersManager.jsx
Added order asc in offers list.
> feat: added order asc in offers list

- src/pages/login/LoginScreen.jsx
- src/pages/register/RegisterScreen.jsx
- src/redux/actions/authActions.js
> refc: remove comments

- src/components/footer/Footer.jsx
- src/components/navbar/Navbar.jsx
- src/components/productList/ProductsList.jsx
- src/components/productList/productList.css
- src/components/productList/productsContainer.jsx
- src/pages/NotFound/NotFound.jsx
- src/pages/NotFound/NotFound.module.css
- src/pages/home/HomeScreen.jsx
- src/pages/login/LoginScreen.jsx
- src/pages/offersManager/OffersManager.jsx
- src/pages/offersManager/OffersManager.module.css
- src/pages/register/RegisterScreen.jsx
- src/pages/shippingpay/ShippingPay.jsx
- src/redux/actions/ProductDetailsActions.js
- src/redux/actions/authActions.js
- src/redux/actions/manageProductsActions.js
- src/redux/actions/offersManagerActions.js
- src/redux/actions/products.js
- src/redux/actions/userActions.js
- src/redux/reducers/offersManagerReducer.js
- src/routes/AppRouter.jsx
Refactoring before deploy.
Remove warnings and errors from the console.
Add the spinner while loading the products.
> Alejandro refactoring before deploy

- src/redux/actions/userActions.js
> refc: remove console.log

- src/components/footer/Footer.jsx
- src/components/footer/Footer.module.css
- src/pages/MisOrdenes/DetalleOrden.jsx
- src/pages/ourteam/OurTeam.jsx
- src/pages/ourteam/OurTeam.module.css
- src/routes/AppRouter.jsx
se agrego pagina de equipo y en el footer
> pagina equipo edicion footer

- src/pages/MisOrdenes/DetalleOrden.jsx
- src/pages/ourteam/OurTeam.jsx
> agregar cambios

- src/components/adminAreaNavbar/AdminAreaNavbar.jsx
- src/pages/offersManager/OffersManager.jsx
- src/pages/usersManager/UsersManager.jsx
- src/pages/usersManager/UsersManager.module.css
- src/redux/actions/usersManagerActions.js
- src/redux/reducers/usersManagerReducer.js
- src/redux/store/store.js
- src/routes/AppRouter.jsx
feat: added users manager feature.
> feat: added users manager feature

- src/redux/actions/ProductDetailsActions.js
- src/redux/actions/products.js
- src/redux/actions/userActions.js
fix: removed environment variables
> fix: removed environment variables

- src/pages/MisOrdenes/GestionDeOrdenes.jsx
- src/pages/MisOrdenes/GestionDeOrdenes.module.css
- src/redux/actions/orderActions.js
- src/redux/reducers/orderReducer.js
- src/routes/AppRouter.jsx
componer rutas para traer todas las ordenes
> actualizar rutas de ordenes

- src/pages/offersManager/OffersManager.module.css
refc: modified offers manager layout
> refc: modified offers manager layout

- src/components/adminAreaNavbar/AdminAreaNavbar.jsx
agregue ordenes en navbar administracion
> add orders navbar admin

- src/pages/MisOrdenes/GestionDeOrdenes.jsx
- src/redux/actions/orderActions.js
- src/redux/reducers/orderReducer.js
ya se esta flitrando las ordenes por su estado
> filtros de ordenes hecho

- src/pages/cart/Cart.jsx
- src/redux/actions/authActions.js
Alejandro fixed login with google.
> Alejandro fixed login with google

- src/components/slider/Slider.jsx
- src/pages/offersManager/OffersManager.jsx
- src/redux/actions/offersManagerActions.js
> Alejandro offers by days
